version: '3.8'

services:
  marpay-redis:
    container_name: marpay-redis
    image: redis:5.0.6-alpine

  marpay-db:
    image: postgres:12.0-alpine
    container_name: marpay-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=marpay_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=spartan123
    ports:
      - 5431:5432 # browse the 5431 in any GUI (e.g. OmniDB)

  marpay-server:
    build:
      context: ./marpay
      dockerfile: Dockerfile_dev
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static
      - ./marpay:/usr/src/app/
    command: daphne --bind 0.0.0.0 --port 8000 marpay.asgi:application
    # command: python manage.py runserver 0.0.0.0:8000
    container_name: marpay-server
    depends_on:
      - marpay-redis
      - marpay-db
    environment:
      - REDIS_URL=redis://marpay-redis:6379/0
      - DATABASE_URL=postgres://root:spartan123@marpay-db:5432/marpay_db # postgres://marpay-db:5432/0
    ports:
      - 8001:8000

  marpay-client:
    build:
      context: ./client
      dockerfile: Dockerfile_dev
    volumes:
      - ./client:/usr/src/app
    command: ng serve --host 0.0.0.0
    container_name: marpay-client
    depends_on:
      - marpay-server
    environment:
      - CHROME_BIN=chromium-browser
    ports:
      - 4201:4200

  marpay-celery:
    build:
      context: ./marpay
      dockerfile: Dockerfile_dev
    command: celery worker --app=marpay --loglevel=info
    container_name: marpay-celery
    volumes:
      - ./marpay:/usr/src/app
    environment:
      - CELERY_BROKER=redis://marpay-redis:6379/0
      - CELERY_BACKEND=redis://marpay-redis:6379/0
    depends_on:
      - marpay-server
      - marpay-redis
      - marpay-db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile_dev
    container_name: marpay-nginx
    depends_on:
      - marpay-server
      - marpay-client
    ports:
      - 8080:80
    restart: always
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static

volumes:
  media:
  static:
  postgres_data: