# Generated by Django 3.0.7 on 2020-06-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'customer'), (2, 'telehealthworker'), (3, 'physician')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='roles',
            field=models.ManyToManyField(to='myuser.Role'),
        ),
    ]
