# Generated by Django 3.0.7 on 2020-06-07 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20200607_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record_summary', models.CharField(max_length=300)),
                ('insurance_provider_summary', models.CharField(max_length=300)),
                ('payment_profile_summary', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myuser.MyUserDetails'),
        ),
    ]
