# Generated by Django 3.0.7 on 2020-06-16 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20200612_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='customer_details',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='physician_details',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='telehealthworker_details',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='physiciandetails',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physician_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telehealthworkerdetails',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telehealthworker_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
