# Generated by Django 3.0.7 on 2020-06-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_auto_20200607_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_details',
        ),
    ]
