# Generated by Django 3.0.7 on 2020-06-30 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('myuser', '0003_auto_20200616_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='current_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_group', to='auth.Group'),
        ),
    ]
