# Generated by Django 3.0.7 on 2020-06-23 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medsession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medsession',
            name='session_attendants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medsession',
            name='session_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
