# Generated by Django 3.0.7 on 2020-06-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsession', '0003_auto_20200623_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='medsession',
            name='session_address_for_telehealthworker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medsession',
            name='session_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
