# Generated by Django 3.0.7 on 2020-07-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsession', '0005_auto_20200703_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='medsession',
            name='status_to_physician',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('STARTED', 'STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='REQUESTED', max_length=20),
        ),
    ]
