
FROM nginx:1.17.5-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY /include.websocket_dev /etc/nginx/app/include.websocket
COPY /include.forwarded_dev /etc/nginx/app/include.forwarded
COPY /dev.conf /etc/nginx/conf.d