# marpay/Dockerfile

FROM python:3.8.3-alpine

RUN apk add --update --no-cache \
    g++ gcc libxslt-dev musl-dev python3-dev \
    libffi-dev openssl-dev jpeg-dev zlib-dev 

ENV LIBRARY_PATH=/lib:/usr/lib

# set environment variables
# Prevents Python from writing pyc files to disc and from buffering stdout and stderr 
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app

# for sql dependencies and still use alpine
RUN apk add --no-cache mariadb-connector-c-dev ;\
    apk add --no-cache --virtual .build-deps \
        build-base \
        mariadb-dev ;\
    pip install mysqlclient;\
    apk del .build-deps 

# for postgres dependencies... psycopg2
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
# RUN python3 -m pip install psycopg2

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt


COPY . /usr/src/app

# RUN mkdir -p /usr/src/app/marpay
# WORKDIR /usr/src/app

RUN python manage.py collectstatic --noinput
# RUN python manage.py makemigrations
# RUN python manage.py migrate
